version: '3.8'

services:
 postgres:
   container_name: postgres
   image: postgres:latest
   restart: always
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
   ports:
     - 5432:5432

 backend:
   container_name: backend
   build: ./Back
   restart: always
   ports:
    - "127.0.0.1:4000:4000"
   depends_on:
    - postgres

 frontend:
   container_name: frontend
   build: ./Front
   restart: always
   ports:
    - "127.0.0.1:3000:3000"
   depends_on: 
    - backend